reservation:
    resource: "@ReservationBundle/Controller/"
    type:     annotation
    prefix:   /

main:
    #resource: "@mainBundle/Resources/config/routing.yml"
    resource: "@mainBundle/Controller"
    type: annotation
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
